query Destinos($locale: Locale!) {
  destinos(orderBy: orden_ASC, locales: [$locale], where: {name_not_starts_with: "\\_"}) {
    name
    description
    image {
      url
    }
    tours {
      id
      nombreDelTour
      precioAproximado
      caracterDeTour
      slug
      image {
        url
      }
      orden
    }
  }
}
