query Destinos {
  destinos(orderBy: orden_ASC) {
    name
    description
    image {
      url
    }
    tours {
      id
      nombreDelTour
      precioAproximado
      caracterDeTour
      slug
      image {
        url
      }
      orden
    }
  }
}
